### PR TITLE
Partially fix Brewmaster's void spirit / brewling

### LINKED ISSUE #91: Brewmaster Void panda not moving  (7.33c)
Looks like Brewmaster doesn't know he has a Void panda  :)

### PR DESCRIPTION
**Pull request by JoshdanG**
Void brewling will now move and attack
Using Astral Pull does not seem to be supported by the Bot API

Also removes old abilities (Corrosive Haze, Drunken Brawler, Thunder Clap) Brewlings no longer gain these abilities from aghs

Illusions go roughly in the direction they decide instead of totally random

Minor reorganization to remove duplicate code

Partially fixes #91

### CODE REVIEW

**Review by ArcherWayne — APPROVED** [review]

**Review by adamqqqplay — APPROVED** [review]
Thanks for your work!
I have a small suggestion: the commit information could be divided into sections, which can be easily read by other developers.

**Comment by JoshdanG** [comment]
> Thanks for your work!
> I have a small suggestion: the commit information could be divided into sections, which can be easily read by other developers.

Will do. Mashing together a combination multiple refactor and then logical changes definitely made this harder to review than necessary.

**Comment by adamqqqplay** [comment]
> > Thanks for your work!
> > I have a small suggestion: the commit information could be divided into sections, which can be easily read by other developers.
> 
> Will do. Mashing together a combination multiple refactor and then logical changes definitely made this harder to review than necessary.

Thanks for your understanding. But maybe I didn't make it clear before, in addition to submitting multiple separate commits, you could also describe changes in multiple points in one commit. Just like the commit information I modified on the master branch.

The commit style of each project may be different, but they all have something in common. For further understanding, please refer to: https://reflectoring.io/meaningful-commit-messages/

**Comment by JoshdanG** [comment]
> > 
> 
> Thanks for your understanding. But maybe I didn't make it clear before, in addition to submitting multiple separate commits, you could also describe changes in multiple points in one commit. Just like the commit information I modified on the master branch.
> 
> The commit style of each project may be different, but they all have something in common. For further understanding, please refer to: https://reflectoring.io/meaningful-commit-messages/

I did get a bit confused there.  I think I _am_ separating my commit messages into several chunks (separated by empty lines), but I will number them to make that clearer and consistent with the rest of the project.

**Pull request merged**
